const dict = {
  it: {
    //GENERIC
    welcome: "Benvenuto",
    start: "Inizia",
    openNavigator: "Apri navigatore",
    time: "Sono le",
    itineraries: "Itinerari",
    events: "Eventi",
    get_inspired: "Lasciati Inspirare",
    open: "Apri",
    filterBy: "Filtra per",
    description: "Descrizione",
    discoverMore: "Scopri di più",
    nearToYou: "Vicini a te",
    nearTo: "Vicini a",
    myPreferences: "I miei gusti",
    access: "ACCEDI",
    login: "Login!",
    loginText: "Registrandoti vedrai contenuti personalizzati in base alle tue preferenze",
    skip: "SALTA",
    exploreAccomodation: "Esplora le strutture ricettive",
    logout: "Disconnetti",
    login: "Accedi",
    showMap: "MOSTRA MAPPA",
    whereToGo: "Esplora dove andare",
    exploreItineraries: "Esplora gli itinerari",
    exploreEvents: "Esplora gli eventi",
    explore: "Esplora",
    gallery: "Foto e video",
    stages: "Le tappe",
    whyVisit: "Perchè visitarlo?",
    usefulInfo: "Info Utili",
    howToReach: "Arrivare in Sardegna",
    howToRoam: "Muoversi in Sardegna",
    craft: "Artigianato",
    centenarians: "Centenari",
    myth: "Mito",
    pristineBlu: "Blu Incontaminato",
    tradition: "Tradizione",
    wildNature: "Natura Selvaggia",
    favouritesPlaces: "DOVE ANDARE",
    favouritesInspirers: "COSA FARE",
    favouritesEvents: "EVENTI",
    favouriteItineraries: "ITINERARI",
    favouriteAccomodations: "STRUTTURE RICETTIVE",
    noFavourites: "Nessun preferito",
    canBeOfInterest: "Potrebbe interessarti anche",
    extrasWildNature: "Natura Selvaggia", 
    extrasMythIsland: "Isola del mito", 
    extrasCentenaryLand: "La terra dei Centenari", 
    extrasLiveTheSea: "Vivere il Mare",
    findOutMore: "APPROFONDISCI",
    open3DModel: "APRI IL MODELLO 3D",
    address: "Indirizzo",
    phone: "Telefono",
    website: "Sito Web",
    email: "Email",
    addressModalTitle: "Dove siamo",
    phoneModalTitle: "Chiama la struttura",
    websiteModalTitle: "Guarda il sito",
    emailModalTitle: "Manda una mail",
    addressOnPressAlert: "Guarda dove troverai la struttura e segui le indicazioni per trovarla.",
    phoneOnPressAlert: "Mettiti direttamente in contatto con la struttura per richiedere informazioni o fare una prenotazione.",
    websiteOnPressAlert: "Naviga la pagina web della struttura per avere maggiori informazioni.",
    emailOnPressAlert: "Mettiti direttamente in contatto con la struttura per richiedere informazioni o fare una prenotazione.",
    addressOnPressBtnTitle: "Naviga",
    phoneOnPressBtnTitle: "Chiama la struttura",
    websiteOnPressBtnTitle: "Vai",
    emailOnPressBtnTitle: "Scrivi",
    //NAVIGATION
    tabWhatToDo: "Cosa fare",
    tabWhereToGo: "Dove andare",
    tabExtras: "Sardegna",
    tabItineraries: "Itinerari",
    tabEvents: "Eventi",
    drawerLanguage: "Lingue",
    drawerTab: "Schermata principale",
    drawerSearch: "Cerca",
    preferences: "I miei gusti",
    preferencesText1: "Basta un minuto!",
    preferencesText2: "Aiutaci a capire i tuoi gusti cliccando sulle emoticon.",
    preferencesText3: "Adesso conosciamo i tuoi gusti.",
    back: "Indietro",
    thanks: "Grazie!",
    insertHere: "Cerca",
    favourites: "Preferiti",
    accomodations: "Strutture Ricettive",
    doYouLikeIt: "Ti piace questo tipo di contenuto?",
    //LANGUAGES
    lanItalian: '🇮🇹 Italiano',
    lanEnglish: '🇬🇧 Inglese',
    //AUTH
    name: "Nome", 
    surname: "Cognome", 
    birth: "Data di nascita", 
    country: "Paese", 
    sex: "Sesso",
    confirm: "CONFERMA",
    register: "REGISTRATI",
    next: "AVANTI",
  },
  "en-gb": {
    //GENERIC
    welcome: "Hello",
    start: "Start",
    openNavigator: "Open navigator",
    time: "It\"s",
    itineraries: "Itineraries",
    events: "Events",
    get_inspired: "Get Inspired",
    open: "Open",
    filterBy: "Filter by",
    description: "Description",
    discoverMore: "Discover More",
    nearToYou: "Near to you",
    nearTo: "Near to",
    exploreAccomodation: "Explore accomodations",
    logout: "Logout",
    login: "Login",
    myPreferences: "My preferences",
    access: "REGISTER",
    login: "Login!",
    loginText: "By registering you will be shown contents tailored to your preferences",
    skip: "SKIP",
    exploreItineraries: "Explore itineraries",
    exploreEvents: "Explore events",
    showMap: "SHOW MAP",
    whereToGo: "Explore where to go",
    explore: "Explore",
    gallery: "Photo and Video",
    stages: "Stages",
    whyVisit: "Why visit it?",
    usefulInfo: "Useful Info",
    howToReach: "Getting in Sardinia",
    howToRoam: "Moving in Sardinia",
    craft: "craft",
    centenarians: "centenarians",
    myth: "myth",
    pristineBlu: "pristine blu",
    tradition: "tradition",
    wildNature: "wild nature",
    favouritesPlaces: "PLACES",
    favouritesEvents: "EVENTS",
    favouriteItineraries: "ITINERARIES",
    favouriteAccomodations: "ACCOMODATIONS",
    noFavourites: "There are no favourites",
    canBeOfInterest: "You can be interested also to",
    extrasWildNature: "Wild Nature", 
    extrasMythIsland: "The Island of the Myth", 
    extrasCentenaryLand: "The Island of the Centenaries", 
    extrasLiveTheSea: "Live the Sea",
    findOutMore: "FIND OUT MORE",
    open3DModel: "OPEN 3D MODEL",
    address: "Address",
    phone: "Phone",
    website: "Website",
    email: "Email",
    addressModalTitle: "Navigate to address",
    phoneModalTitle: "Call",
    websiteModalTitle: "Browse the website",
    emailModalTitle: "Send an email",
    addressOnPressAlert: "Do you want to open the navigator?",
    phoneOnPressAlert: "Do you want to call the host?",
    websiteOnPressAlert: "Do you want to navigate to the host's website?",
    emailOnPressAlert: "Do you want to open the email client?",
    addressOnPressBtnTitle: "Go!",
    phoneOnPressBtnTitle: "Call the host",
    websiteOnPressBtnTitle: "Open browser",
    emailOnPressBtnTitle: "Open email",
    //NAVIGATION
    tabWhatToDo: "What to do",
    tabWhereToGo: "Where to go",
    tabExtras: "Sardinia",
    tabItineraries: "Itineraries",
    tabEvents: "Events",
    drawerLanguage: "Languages",
    drawerTab: "Main screen",
    preferences: "My preferences",
    preferencesText1: "It only takes a minute!",
    preferencesText2: "Help us understand your preferences by clicking on the emoticons.",
    preferencesText3: "Now we know your preferences.",
    back: "Back",
    thanks: "Thanks!",
    drawerSearch: "Search",
    insertHere: "Search",
    favourites: "Favourites",
    accomodations: "Accomodations",
    doYouLikeIt: "Do you like this content",
    //LANGUAGES
    lanItalian: '🇮🇹 Italian',
    lanEnglish: '🇬🇧 English',
    //AUTH
    name: "Name", 
    surname: "Surname", 
    birth: "Birth date", 
    country: "Country", 
    sex: "Sex",
    confirm: "CONFIRM",
    register: "REGISTER",
    next: "NEXT",
  }
}

export default dict;
