import  { normalizeLanguage } from '../helpers/utils';

const itKey = normalizeLanguage("it");
const enKey = normalizeLanguage("en-*");
const zhKey = normalizeLanguage("zh-*");
const frKey = normalizeLanguage("fr");
const deKey = normalizeLanguage("de");

const dict = {
  [itKey]: {
    //GENERIC
    man: "Uomo",
    woman: "Donna",
    welcome: "Benvenuto",
    start: "Inizia",
    go: "VAI",
    openNavigator: "Vai al navigatore",
    openMap: "Apri la mappa",
    time: "Sono le",
    itineraries: "Itinerari",
    events: "Eventi",
    get_inspired: "Lasciati Inspirare",
    open: "Apri",
    filterBy: "Filtra per",
    description: "Descrizione",
    discoverMore: "Scopri di più",
    nearToYou: "Vicini a te",
    nearTo: "Vicini a",
    myPreferences: "I miei gusti",
    access: "ACCEDI",
    loginText: "Registrandoti vedrai contenuti personalizzati in base alle tue preferenze",
    skip: "SALTA",
    exploreAccomodation: "Esplora le strutture ricettive",
    nearAccomodations: "Strutture ricettive nelle vicinanze",
    logout: "Disconnetti",
    login: "Accedi",
    completeAccess: "Completa Profilo",
    showMap: "MOSTRA MAPPA",
    whereToGo: "Esplora dove andare",
    exploreItineraries: "Esplora gli itinerari",
    exploreEvents: "Esplora gli eventi",
    exploreEventsOnMap: "Esplora gli eventi sulla mappa",
    filterEvents: "Flitra gli eventi",
    filter: "FILTRA",
    explore: "Esplora",
    startTrip: "Inizia il tuo viaggio",
    chooseAccomodation: "Scegli dove alloggiare",
    whatToSee: "Scegli cosa vedere",
    gallery: "Galleria",
    stages: "Le tappe",
    whyVisit: "Perchè visitarlo?",
    usefulInfo: "Info Utili",
    howToReach: "Arrivare in Sardegna",
    howToRoam: "Muoversi in Sardegna",
    craft: "Artigianato",
    centenarians: "Terra dei Centenari",
    culture: "Culture",
    myth: "Mito",
    pristineBlu: "Blu Incontaminato",
    tradition: "Tradizione",
    wildNature: "Natura",
    starredPlaces: "Luoghi del cuore",
    favouritesPlaces: "DOVE ANDARE",
    favouritesInspirers: "COSA FARE",
    favouritesEvents: "EVENTI",
    favouriteItineraries: "ITINERARI",
    favouriteAccomodations: "STRUTTURE RICETTIVE",
    noFavourites: "Nessun preferito",
    canBeOfInterest: "Potrebbe interessarti anche",
    extrasWildNature: "Natura", 
    extrasMythIsland: "Mito", 
    extrasTradition: "Tradizioni", 
    extrasCentenaryLand: "Centenari", 
    extrasLiveTheSea: "Mare",
    extrasStarredPlaces: "Luoghi del cuore",
    extrasCulture: "Cultura",
    findOutMore: "APPROFONDISCI",
    open3DModel: "Esplora la <br/>Realtà Virtuale",
    address: "Indirizzo",
    phone: "Telefono",
    website: "Sito Web",
    email: "Email",
    addressModalTitle: "Dove siamo",
    phoneModalTitle: "Chiama la struttura",
    websiteModalTitle: "Guarda il sito",
    emailModalTitle: "Manda una mail",
    addressOnPressAlert: "Guarda dove troverai la struttura e segui le indicazioni per trovarla.",
    phoneOnPressAlert: "Mettiti direttamente in contatto con la struttura per richiedere informazioni o fare una prenotazione.",
    websiteOnPressAlert: "Naviga la pagina web della struttura per avere maggiori informazioni.",
    emailOnPressAlert: "Mettiti direttamente in contatto con la struttura per richiedere informazioni o fare una prenotazione.",
    addressOnPressBtnTitle: "Naviga",
    phoneOnPressBtnTitle: "Chiama la struttura",
    websiteOnPressBtnTitle: "Vai",
    emailOnPressBtnTitle: "Scrivi",
    entityIsNotTranslated: "Questa entità non ha una traduzione per la lingua corrente",
    retry: "Riprova",
    //LOGIN
    possibleCauses: "Possibili cause:",
    reusedOldLink: "• È stato usato un link di login scaduto o già utilizzato",
    alreadyLoggedIn: "• Il login è stato già effettuato precedentemente",
    connectionIssues: "• La connessione ad internet è inattiva o intermittente",
    unsuccessfulLogin: "Il login non è andato a buon fine, si prega di riprovare.",
    //NAVIGATION
    tabWhatToDo: "Cosa fare",
    tabWhereToGo: "Dove andare",
    tabExtras: "Sardegna",
    tabItineraries: "Itinerari",
    tabEvents: "Eventi",
    drawerLanguage: "Lingue",
    drawerTab: "Schermata principale",
    drawerSearch: "Cerca",
    preferences: "I miei gusti",
    preferencesText1: "Basta un minuto!",
    preferencesText2: "Aiutaci a capire i tuoi gusti cliccando sulle emoticon.",
    preferencesText3: "Adesso conosciamo i tuoi gusti.",
    back: "Indietro",
    okDoneSurvey: "OK, HAI FINITO!",
    thanks: "Grazie!",
    insertHere: "Cerca",
    favourites: "Preferiti",
    accomodations: "Strutture Ricettive",
    doYouLikeIt: "Ti piace questo tipo di contenuto?",
    //LANGUAGES
    lanItalian: '🇮🇹 Italiano',
    lanEnglish: '🇬🇧 Inglese',
    //AUTH
    profile: 'Profilo',
    username: "Inserisci un nome", 
    name: "Nome", 
    surname: "Cognome", 
    birth: "Data di nascita", 
    country: "Paese", 
    sex: "Sesso",
    confirm: "Conferma",
    register: "Registrati",
    next: "Avanti",
    sentLink: "Ti abbiamo mandato un link", 
    checkInbox: "Controlla la tua mail",
    logoutMsg: "Vuoi disconnettere il tuo account?",
    logoutBtn: "Disconnetti",
    removeProfileMsg: "Vuoi rimuovere il tuo profilo?",
    removeProfileBtn: "Rimuovi Profilo",
    editProfileBtn: "Modifica Profilo",
    fillInformation: "Inserisci qui i tuoi dati",
    unsuccessfullLogin: "Siamo spiacenti ma il login è fallito",
    successfullLogin: "Autenticazione riuscita!",
    loggingIn: "Login in corso..",
    loginError: "Errore di login:",
    //Parks
    nearParks: "Parcheggi nelle vicinanze!", 
    discoverParks: "Scopri i parcheggi liberi più vicini a te attraverso uno dei servizi convenzionati.",
    findParkBtn: "TROVA UN PARCHEGGIO",
    //Update
    updateInProgressText: "AGGIORNAMENTO IN CORSO", 
    updateFinishedText: "AGGIORNAMENTO TERMINATO, RIAVVIO IN CORSO...",
    //Networking
    disconnected: "Disconnesso...",
    pleaseConnect: "Riattiva la connessione per utilizzare l'applicazione",
    //App Location Tracking background
    notificationTitle: "L'app Sardinia ti avvisa",
    notificationBody: "Sei vicino ad un punto di interesse!",
  },
  [enKey]: {
    //GENERIC
    man: "Man",
    woman: "Woman",
    welcome: "Hello",
    go: "GO",
    start: "Start",
    openNavigator: "Open navigator",
    openMap: "Open map",
    time: "It\"s",
    itineraries: "Itineraries",
    events: "Events",
    get_inspired: "Get Inspired",
    open: "Open",
    filterBy: "Filter by",
    description: "Description",
    discoverMore: "Discover More",
    nearToYou: "Near to you",
    nearTo: "Near to",
    exploreAccomodation: "Explore accomodations",
    nearAccomodations: "Nearest accomodations",
    logout: "Logout",
    login: "Login",
    myPreferences: "My preferences",
    access: "REGISTER",
    completeAccess: "Complete profile",
    loginText: "By registering you will be shown contents tailored to your preferences",
    skip: "SKIP",
    exploreItineraries: "Explore itineraries",
    exploreEvents: "Explore events",
    exploreEventsOnMap: "Explore events on map",
    filterEvents: "Filter events",
    filter: "FILTER",
    showMap: "SHOW MAP",
    whereToGo: "Explore where to go",
    explore: "Explore",
    startTrip: "Start your trip",
    chooseAccomodation: "Choose where to stay",
    whatToSee: "Choose what to see",
    gallery: "Gallery",
    stages: "Stages",
    whyVisit: "Why visit it?",
    usefulInfo: "Useful Info",
    howToReach: "Getting in Sardinia",
    howToRoam: "Moving in Sardinia",
    craft: "craft",
    centenarians: "centenarians",
    myth: "myth",
    culture: "culture",
    pristineBlu: "pristine blu",
    tradition: "tradition",
    wildNature: "nature",
    starredPlaces: "Places of the Hearth",
    favouritesPlaces: "PLACES",
    favouritesEvents: "EVENTS",
    favouriteItineraries: "ITINERARIES",
    favouriteAccomodations: "ACCOMODATIONS",
    noFavourites: "There are no favourites",
    canBeOfInterest: "You can be interested also to",
    extrasWildNature: "Nature", 
    extrasMythIsland: "The Island of the Myth", 
    extrasTradition: "Tradition", 
    extrasCentenaryLand: "The Island of the Centenaries", 
    extrasLiveTheSea: "Sea",
    extrasCulture: "Culture",
    extrasStarredPlaces: "Places of the Hearth",
    findOutMore: "FIND OUT MORE",
    open3DModel: "OPEN 3D MODEL",
    address: "Address",
    phone: "Phone",
    website: "Website",
    email: "Email",
    addressModalTitle: "Navigate to address",
    phoneModalTitle: "Call",
    websiteModalTitle: "Browse the website",
    emailModalTitle: "Send an email",
    addressOnPressAlert: "Do you want to open the navigator?",
    phoneOnPressAlert: "Do you want to call the host?",
    websiteOnPressAlert: "Do you want to navigate to the host's website?",
    emailOnPressAlert: "Do you want to open the email client?",
    addressOnPressBtnTitle: "Go!",
    phoneOnPressBtnTitle: "Call the host",
    websiteOnPressBtnTitle: "Open browser",
    emailOnPressBtnTitle: "Open email",
    entityIsNotTranslated: "This entity hasn't got a translation for the current language",
    retry: "Retry",
    //LOGIN
    possibleCauses: "Possible causes:",
    reusedOldLink: "• The login link has already been used or is expired",
    alreadyLoggedIn: "• Login was already performed",
    connectionIssues: "• Internet connection is inactive or poor",
    unsuccessfulLogin: "Login unsuccessful. Please retry",
    //NAVIGATION
    tabWhatToDo: "What to do",
    tabWhereToGo: "Where to go",
    tabExtras: "Sardinia",
    tabItineraries: "Itineraries",
    tabEvents: "Events",
    drawerLanguage: "Languages",
    drawerTab: "Main screen",
    preferences: "My preferences",
    preferencesText1: "It only takes a minute!",
    preferencesText2: "Help us understand your preferences by clicking on the emoticons.",
    preferencesText3: "Now we know your preferences.",
    back: "Back",
    okDoneSurvey: "OK, YOU ARE DONE!",
    thanks: "Thanks!",
    drawerSearch: "Search",
    insertHere: "Search",
    favourites: "Favourites",
    accomodations: "Accomodations",
    doYouLikeIt: "Do you like this content",
    //LANGUAGES
    lanItalian: '🇮🇹 Italian',
    lanEnglish: '🇬🇧 English',
    //AUTH
    profile: 'Profile',
    username: "Username", 
    name: "Name", 
    surname: "Surname", 
    birth: "Birth date", 
    country: "Country", 
    sex: "Sex",
    confirm: "Confirm",
    register: "Register",
    next: "Next",
    sentLink: "We've sent you a link", 
    checkInbox: "Check your inbox",
    logoutMsg: "Do you want to logout from your account?",
    logoutBtn: "Logout",
    removeProfileMsg: "Do you want to delete your profile?",
    removeProfileBtn: "Delete Profile",
    editProfileBtn: "Edit Profile",
    fillInformation: "Fill in the personal data form",
    unsuccessfullLogin: "We are sorry but the login was unsuccessful",
    successfullLogin: "Authentication successful!",
    loggingIn: "Logging in..",
    loginError: "Error loggin in:",
    //Parks
    nearParks: "Nearest parkings!", 
    discoverParks: "Discover the nearest free parkings provided by one of the affiliated services.",
    findParkBtn: "FIND A PARK",
    //Update
    updateInProgressText: "UPDATE IN PROGRESS", 
    updateFinishedText: "UPDATE FINISHED, RESTARTING...",
    //Networking
    disconnected: "Disconnected...",
    pleaseConnect: "Please turn on internet connection to access the app contents",
    //App Location Tracking background
    notificationTitle: "Sardinia App Location",
    notificationBody: "Sardinia App is tracking your location",
  },
  zhKey: {},
  frKey: {},
  deKey: {},
}

export default dict;
